// S1 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    level._effect["mp_lair_jumping_fountain_ct_nozzle"] = loadfx( "vfx/map/mp_lair/mp_lair_jumping_fountain_ct_nozzle" );
    level._effect["mp_lair_jumping_fountain_nozzle"] = loadfx( "vfx/map/mp_lair/mp_lair_jumping_fountain_nozzle" );
    level._effect["mp_lair_jumping_fountain_splash"] = loadfx( "vfx/map/mp_lair/mp_lair_jumping_fountain_splash" );
    level._effect["mp_lair_godray_vista_dusty"] = loadfx( "vfx/map/mp_lair/mp_lair_godray_vista_dusty" );
    level._effect["mp_lair_boat_foam"] = loadfx( "vfx/map/mp_lair/mp_lair_boat_foam" );
    level._effect["mp_lair_big_fountain_geyser_burst"] = loadfx( "vfx/map/mp_lair/mp_lair_big_fountain_geyser_burst" );
    level._effect["mp_lair_jumping_fountain_center"] = loadfx( "vfx/map/mp_lair/mp_lair_jumping_fountain_center" );
    level._effect["mp_lair_jumping_fountain"] = loadfx( "vfx/map/mp_lair/mp_lair_jumping_fountain" );
    level._effect["mp_lair_roof_smoke"] = loadfx( "vfx/map/mp_lair/mp_lair_roof_smoke" );
    level._effect["mp_lair_fountian_geyser"] = loadfx( "vfx/map/mp_lair/mp_lair_fountian_geyser" );
    level._effect["mp_lair_fountian_foam"] = loadfx( "vfx/map/mp_lair/mp_lair_fountian_foam" );
    level._effect["fountain_water_distortion"] = loadfx( "vfx/map/mp_lair/fountain_water_distortion" );
    level._effect["mp_lair_searchlights_far"] = loadfx( "vfx/map/mp_lair/mp_lair_searchlights_far" );
    level._effect["mp_lair_ambient_boats_idle"] = loadfx( "vfx/map/mp_lair/mp_lair_ambient_boats_idle" );
    level._effect["insects_flies_landing"] = loadfx( "vfx/animal/dlc/insects_flies_landing" );
    level._effect["mp_lair_clouds_oriented_vista"] = loadfx( "vfx/map/mp_lair/mp_lair_clouds_oriented_vista" );
    level._effect["mp_lair_fountain_coins"] = loadfx( "vfx/map/mp_lair/mp_lair_fountain_coins" );
    level._effect["lib_birds_runner"] = loadfx( "vfx/map/mp_liberty/lib_birds_runner" );
    level._effect["mp_lair_boat_blinking_light_01"] = loadfx( "vfx/map/mp_lair/mp_lair_boat_blinking_light_01" );
    level._effect["mp_lair_falling_vista_needles"] = loadfx( "vfx/map/mp_lair/mp_lair_falling_vista_needles" );
    level._effect["mp_lair_boat_blinking_light"] = loadfx( "vfx/map/mp_lair/mp_lair_boat_blinking_light" );
    level._effect["mp_lair_vista_fireworks_far"] = loadfx( "vfx/map/mp_lair/mp_lair_vista_fireworks_far" );
    level._effect["mp_lair_ambient_boats"] = loadfx( "vfx/map/mp_lair/mp_lair_ambient_boats" );
    level._effect["mp_lair_big_fountain_arcs"] = loadfx( "vfx/map/mp_lair/mp_lair_big_fountain_arcs" );
    level._effect["mp_lair_ground_loop_blue_runner"] = loadfx( "vfx/map/mp_lair/mp_lair_ground_loop_blue_runner" );
    level._effect["mp_lair_big_fountain_splash"] = loadfx( "vfx/map/mp_lair/mp_lair_big_fountain_splash" );
    level._effect["mp_lair_ground_grassdirt_loop_blue"] = loadfx( "vfx/map/mp_lair/mp_lair_ground_grassdirt_loop_blue" );
    level._effect["mp_lair_building_blink"] = loadfx( "vfx/map/mp_lair/mp_lair_building_blink" );
    level._effect["mp_lair_light_flares"] = loadfx( "vfx/map/mp_lair/mp_lair_light_flares" );
    level._effect["mp_lair_vista_fireworks"] = loadfx( "vfx/map/mp_lair/mp_lair_vista_fireworks" );
    level._effect["mp_lair_big_fountain"] = loadfx( "vfx/map/mp_lair/mp_lair_big_fountain" );
    level._effect["mp_lair_fountian_splash_top_line_runner"] = loadfx( "vfx/map/mp_lair/mp_lair_fountian_splash_top_line_runner" );
    level._effect["mp_lair_pedal_loop_blue_runner"] = loadfx( "vfx/map/mp_lair/mp_lair_pedal_loop_blue_runner" );
    level._effect["insects_flit_moths_complex"] = loadfx( "vfx/animal/dlc/insects_flit_moths_complex" );
    level._effect["mp_lair_ambient_air_dust"] = loadfx( "vfx/map/mp_lair/mp_lair_ambient_air_dust" );
    level._effect["mp_lair_ground_loop_red_runner"] = loadfx( "vfx/map/mp_lair/mp_lair_ground_loop_red_runner" );
    level._effect["mp_lair_ground_loop_purple_runner"] = loadfx( "vfx/map/mp_lair/mp_lair_ground_loop_purple_runner" );
    level._effect["cli_insect_dragonfly_runner"] = loadfx( "vfx/map/mp_climate/cli_insect_dragonfly_runner" );
    level._effect["mp_lair_fountian_splash_line_runner"] = loadfx( "vfx/map/mp_lair/mp_lair_fountian_splash_line_runner" );
    level._effect["mp_lair_speaker_distort_sml"] = loadfx( "vfx/map/mp_lair/mp_lair_speaker_distort_sml" );
    level._effect["mp_bigb_searchlights"] = loadfx( "vfx/map/mp_bigben/mp_bigb_searchlights" );
    level._effect["mp_lair_ac_smoke"] = loadfx( "vfx/map/mp_lair/mp_lair_ac_smoke" );
    level._effect["mp_lair_pedal_loop_red_runner"] = loadfx( "vfx/map/mp_lair/mp_lair_pedal_loop_red_runner" );
    level._effect["mp_lair_pedal_loop_purple_runner"] = loadfx( "vfx/map/mp_lair/mp_lair_pedal_loop_purple_runner" );
    level._effect["dust_falling_runner"] = loadfx( "vfx/dust/dust_falling_runner" );
    level._effect["mp_lair_vista_sand_fog"] = loadfx( "vfx/map/mp_lair/mp_lair_vista_sand_fog" );
    level._effect["mp_lair_speaker_distort"] = loadfx( "vfx/map/mp_lair/mp_lair_speaker_distort" );
    level._effect["mp_lair_ambient_needles_runner"] = loadfx( "vfx/map/mp_lair/mp_lair_ambient_needles_runner" );
    level._effect["mp_ground_ambient_sitting_dust"] = loadfx( "vfx/map/mp_lair/mp_ground_ambient_sitting_dust" );
    level._effect["mp_ground_dirt_loop_runner"] = loadfx( "vfx/map/mp_lair/mp_ground_dirt_loop_runner" );
    level._effect["window_wind_runner"] = loadfx( "vfx/map/mp_lair/window_wind_runner" );
    level._effect["mp_lair_ground_grassdirt_loop_red_runner"] = loadfx( "vfx/map/mp_lair/mp_lair_ground_grassdirt_loop_red_runner" );
    level._effect["mp_lair_goblet_fire"] = loadfx( "vfx/map/mp_lair/mp_lair_goblet_fire" );
    level._effect["bird_seagull_flock_large_flying"] = loadfx( "vfx/animal/bird_seagull_flock_large_flying" );
    level._effect["insects_moths"] = loadfx( "vfx/animal/insects_moths" );
    level._effect["insects_fruitflies_flying"] = loadfx( "vfx/animal/insects_fruitflies_flying" );
    level._effect["butterfly_a_sml_runner"] = loadfx( "vfx/animal/butterfly_a_sml_runner" );
    level._effect["mp_lair_ambient_int_dust"] = loadfx( "vfx/map/mp_lair/mp_lair_ambient_int_dust" );
    level._effect["mp_bigb_falling_leaves_runner"] = loadfx( "vfx/map/mp_bigben/mp_bigb_falling_leaves_runner" );
    level._effect["tesla_lightning_loop_friendly"] = loadfx( "vfx/map/mp_lair/tesla_lightning_loop_friendly" );
    level._effect["tesla_coil_discharging"] = loadfx( "vfx/map/mp_lair/tesla_coil_discharging" );
    level._effect["tesla_coil_charging"] = loadfx( "vfx/map/mp_lair/tesla_coil_charging" );
    level._effect["tesla_coil_active"] = loadfx( "vfx/map/mp_lair/tesla_coil_active" );
    level._effect["lightning_bolt_impact"] = loadfx( "vfx/explosion/lightning_bolt_impact" );
    level._effect["shocked_corpse"] = loadfx( "vfx/sparks/shocked_corpse" );
    level._effect["tesla_lightning_loop"] = loadfx( "vfx/map/mp_lair/tesla_lightning_loop" );
    level._effect["test_effect"] = loadfx( "vfx/test/test_fx" );
    level thread onplayerconnect();
}

onplayerconnect()
{
    for (;;)
    {
        level waittill( "connected", var_0 );
        level thread start_persistent_fx( var_0 );
    }
}

start_persistent_fx( var_0 )
{
    if ( isdefined( level.teslacoilsactivated ) && level.teslacoilsactivated )
        start_vista_vfx( var_0 );
    else
        level thread start_big_fountain( var_0 );

    thread ambient_speed_boats_01( var_0 );
    thread ambient_speed_boats_02( var_0 );
    thread ambient_speed_boats_03( var_0 );
}

start_big_fountain( var_0 )
{
    level thread common_scripts\_exploder::activate_clientside_exploder( 11, var_0 );
}

start_vista_vfx( var_0 )
{
    level thread vista_fireworks( var_0 );
    level notify( "aud_fireworks" );
    level thread fountain_water_show( var_0 );
    wait 1;
    stopclientexploder( 11, var_0 );
    level thread fountain_water_show_center( var_0 );
}

vista_fireworks( var_0 )
{
    level thread common_scripts\_exploder::activate_clientside_exploder( 10, var_0 );
}

fountain_water_show( var_0 )
{
    level thread common_scripts\_exploder::activate_clientside_exploder( 12, var_0 );
}

fountain_water_show_center( var_0 )
{
    level thread common_scripts\_exploder::activate_clientside_exploder( 13, var_0 );
}

ambient_speed_boats_01( var_0 )
{
    level thread common_scripts\_exploder::activate_clientside_exploder( 20, var_0 );
}

ambient_speed_boats_02( var_0 )
{
    level thread common_scripts\_exploder::activate_clientside_exploder( 21, var_0 );
}

ambient_speed_boats_03( var_0 )
{
    level thread common_scripts\_exploder::activate_clientside_exploder( 22, var_0 );
}
