// S1 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

generic_combat()
{
    animscripts\battlechatter::playbattlechatter();
}

specific_combat( var_0 )
{
    animscripts\battlechatter::playbattlechatter();
}
