// S1 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

#using_animtree("generic_human");

main()
{
    if ( self.canjumppath )
        animscripts\traverse\boost::rocket_jump_human( %boost_jump_256_across_128_over, 1 );
}
