// S1 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    self setmodel( "atlas_pmc_body" );
    codescripts\character::attachhead( "alias_pmc_helmet_heads", xmodelalias\alias_pmc_helmet_heads::main() );
    self.voice = "xslice";
    self setclothtype( "vestlight" );
}

precache()
{
    precachemodel( "atlas_pmc_body" );
    codescripts\character::precachemodelarray( xmodelalias\alias_pmc_helmet_heads::main() );
}
