// S1 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    self setmodel( "civ_urban_male_body_f" );
    self attach( "head_m_gen_cau_shipley", "", 1 );
    self.headmodel = "head_m_gen_cau_shipley";
    self.voice = "atlas";
    self setclothtype( "vestlight" );
}

precache()
{
    precachemodel( "civ_urban_male_body_f" );
    precachemodel( "head_m_gen_cau_shipley" );
}
