// S1 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    self setmodel( "civ_urban_female_body_g_afr_light" );
    self attach( "head_f_gen_afr_rice", "", 1 );
    self.headmodel = "head_f_gen_afr_rice";
    self.voice = "american";
    self setclothtype( "vestlight" );
}

precache()
{
    precachemodel( "civ_urban_female_body_g_afr_light" );
    precachemodel( "head_f_gen_afr_rice" );
}
